apiVersion: v1
kind: Secret
metadata:
   name: ninja-secret
stringData:
   ninja: ninjaPassword
data:
   https.cert: MIICvDCCAaQCCQCHqd+QlxmpGDANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBV3d3cua3ViaWEtZXhhbXBsZS5jb20wHhcNMTkwMTE1MDcyMDI0WhcNMjkwMTEyMDcyMDI0WjAgMR4wHAYDVQQDDBV3d3cua3ViaWEtZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVUtK8jtjPF+qA51fxoMDPJWJ1LYB/Nd3t3DfSmC9aZ8ywhITfFUA2thZREdNbedWHNPKFU3ViJh2hjT5udQNS8t4FL2C9qZSSBrrtMfNEDsrX2P/iQTm53Wrfp7B+CngI1KU22/7D0EHq2MWOh3WeldS50JbPkD2Bp9fzZK7r5O3G03OPLqsvl2Ra+9po+lwuGLeunbVm3V9BizvHN9g1VJyvsBK9JYg+Qf0g4oxoBMbYjTemMrtDiQpWaLt/kqN/tjwlJGHLpae11uiNIZ/cMqfnMcmITHmREczudwxxKmPORWIfzeTzlvLKzM/4SNPP4PHslrCdQNeT/RnqXUq9AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGPmpg9Li1RQIPj5o0mzHWa9mF3E9Vo5GPI8L1bndjM19c3MQ4772g1WJSo8jWu5irRrTd1Z/aIwLY18oDgMEvsd+ZIYaUf/KB+fs+aWau8CYdCTM9kCiFNaEWOZiVYVcP5X0fCwH8lC7ioYSqZ6ojaI9aaz/ogBMXq0B7Z5nQIGgiShVoFNnEw8JyY5Ech28Ii7HGaEz74JPrIGbPnVURvXi5oCmqPr3NFvf6oE+kw1Xa+quQIJLmr2Ol50t8Bcdr7RUUQ0T9nf+xuBzbm7huFkMEpjjaubSy+1oF2VMkNbcgyawLn+14hl94rGIBC1kue9yd+f1A4QdXXQNQVOmYE=
