apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-delay
spec:
  containers:
  - image: haja/kubia-unhealth
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
