apiVersion: v1
kind: Pod
metadata:
  name: nginx-boom-with-secrets
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: secretvol
      mountPath: /usr/my/secrets
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: html
    emptyDir: {}
  - name: secretvol
    secret:
      secretName: secret-nginx
    
