# a simple kubernetes manifest
apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-custom
  annotations:
    geckomite.com/register: haja-registr
spec:
  containers:
  - image: haja/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP

